print("--------------------------------------------------")
print("|            STANBIC BANK                        |")
print("|            CBD BRANCH                          |")
print("|           31st August 2023                     |")
print("|                                                |")
print("|First Name : EUNICE                             |")
print("|Second Name : NYABOKE                           |")
print("|ACC NO:     :1140186308131                      |")
print("|ACC Balance :24,000,000,000                     |")
print("|                                                |")
print("--------------------------------------------------")